runtime: python
env: flex
entrypoint: python splatnet2statink.py
threadsafe: true

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    script: splatnet2statink.py
    login: admin
  - url: /.*
    script: splatnet2statink.py
    login: admin

# liveness_check:
#   path: "/"
#   check_interval_sec: 300
#   timeout_sec: 30
#   failure_threshold: 5
#   success_threshold: 2

includes:
  - secret.yaml